# Docker-compose provided by Kevin Allioli
# Last update : 01/05/2023

# Environment variables to declare :
#     - SERVICE : name of the service (example : synapse)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : uptime.domain.tld)
#     - DATA_LOCATION : files downloaded location (example /app/"service")
#     - NETWORK_APP : application network name

# Work with Portainer

version: '3.9'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    #healthcheck:
    #  test: curl --fail http://localhost:8080/auth/realms/master
    #  interval: 10s
    #  timeout: 5s
    #  retries: 3
    deploy:
      placement:
        constraints:
        - node.role == worker
        - node.labels.general == true
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_network
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.$SERVICE.entrypoints=https
        - traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)
        - traefik.http.services.$SERVICE.loadbalancer.server.port=3001
    volumes:
      - $DATA_LOCATION:/app/data

    networks:
      - traefik_network

networks:
  traefik_network:
    external: true