# Docker-compose provided by Kevin Allioli
# Last update : 04/05/2023

# Environment variables to declare :
#     - SERVICE : name of the service (example : filebrowser)
#     - PUID : system user id (example : 1001)
#     - PGID : system group id (example : 1001)
#     - TZ : container time zone (example : Europe/Paris)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - JSON_CONFIG_FILE : location of config.json file
#     - BRANDING_DIR : location of service customization folder (example /app/"service"/customization) 
#     - DB_FILE : location of database.db file
#     - FQDN : fully qualified domain name (example : filebrowser.domain.tld)

# Work with Portainer

version: "3.9"
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:80'
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - $DATA_LOCATION:/srv
      - $JSON_CONFIG_FILE:/config/settings.json
      - $DB_FILE:/database/filebrowser.db
      - $BRANDING_DIR:/customization
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=80"
      - "traefik.docker.network=app-network"
    networks:
      - app-network

networks:
  app-network:
    external: true