# Docker-compose provided by Kevin Allioli
# Last update : 0i3/05/2023

# Environment variables to declare :
#     - SERVICE : name of the service (example : plex)
#     - VERSION : deployed version (example : latest)
#     - PUID : system user id (example : 1001)
#     - PGID : system group id (example : 1001)
#     - TZ : container time zone (example : Europe/Paris)
#     - CONFIG_DATA_LOCATION : location of configuration service data (example /app/"service")
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - TRANSCODE_DATA_LOCATION : data transcode location 

# Work with Portainer

version: '3.9'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - VERSION=$VERSION
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:32400/identity" > /dev/null
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - $CONFIG_DATA_LOCATION:/config
      - $DATA_LOCATION:/data
      - $TRANSCODE_DATA_LOCATION:/transcode
    network_mode: host